services:
  - type: web
    name: rss-feed-processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/runner.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 