name: Deploy RSS Feed Processor to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest tests/ -v || true  # Don't fail deployment if tests fail, remove '|| true' if you want strict testing

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        # Using curl to trigger Render.com deploy hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      - name: Verify Deployment
        run: |
          echo "Deployment triggered successfully"
          echo "Check status at https://dashboard.render.com" 